//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_Order_Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_client
    {
        public ct_client()
        {
            this.or_order = new HashSet<or_order>();
        }
    
        public int ct_client_id { get; set; }
        public string ct_client_source { get; set; }
        public string us_user_name { get; set; }
        public System.DateTime ct_create_time { get; set; }
        public string ct_client_name { get; set; }
        public string ct_status { get; set; }
        public string ct_client_tel { get; set; }
        public string ct_client_qq { get; set; }
        public Nullable<System.DateTime> ct_wedding_day { get; set; }
        public string ct_reach_status { get; set; }
        public string ct_order_status { get; set; }
        public string ct_express { get; set; }
        public Nullable<double> ct_freight { get; set; }
        public string ct_address { get; set; }
        public string ct_remark { get; set; }
    
        public virtual ICollection<or_order> or_order { get; set; }
    }
}
