//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_Order_Storage
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ct_client
    {
        public ct_client()
        {
            this.or_order = new HashSet<or_order>();
        }

        [Required]
        public int ct_client_id { get; set; }

        [Display(Name = "客户来源")]
        public string ct_client_source { get; set; }

        [Display(Name = "其他")]
        public string ct_client_source_cst { get; set; }

        [Required]
        [Display(Name = "用户名")]
        public string us_user_name { get; set; }

        [Required]
        [Display(Name = "创建时间")]
        public System.DateTime ct_create_time { get; set; }

        [Required]
        [Display(Name = "客户名")]
        public string ct_client_name { get; set; }

        [Required]
        [Display(Name = "状态")]
        public string ct_status { get; set; }

        [Required]
        [Display(Name = "手机号码")]
        public string ct_client_tel { get; set; }

        [Display(Name = "QQ")]
        public string ct_client_qq { get; set; }

        [Display(Name = "婚期")]
        public Nullable<System.DateTime> ct_wedding_day { get; set; }

        [Display(Name = "到店状态")]
        public string ct_reach_status { get; set; }

        [Display(Name = "订单状态")]
        public string ct_order_status { get; set; }

        public string ct_express { get; set; }

        public Nullable<double> ct_freight { get; set; }

        public string ct_address { get; set; }

        [Display(Name = "备注")]
        public string ct_remark { get; set; }
    
        public virtual ICollection<or_order> or_order { get; set; }
    }
}
