//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_Order_Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_inventory
    {
        public in_inventory()
        {
            this.or_order = new HashSet<or_order>();
            this.st_stock = new HashSet<st_stock>();
        }
    
        public int in_inventory_id { get; set; }
        public string in_inventory_type { get; set; }
        public string us_user_name { get; set; }
        public System.DateTime in_create_time { get; set; }
        public byte[] in_image { get; set; }
        public string in_style_id { get; set; }
        public string in_style_name { get; set; }
        public string in_status { get; set; }
        public string in_color { get; set; }
        public string in_size { get; set; }
        public Nullable<double> in_eur { get; set; }
        public Nullable<double> in_usd { get; set; }
        public Nullable<double> in_cny { get; set; }
        public Nullable<int> in_amount { get; set; }
        public string in_remark { get; set; }
    
        public virtual ICollection<or_order> or_order { get; set; }
        public virtual ICollection<st_stock> st_stock { get; set; }
    }
}
