//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_Order_Storage
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class in_inventory
    {
        public in_inventory()
        {
            this.or_order = new HashSet<or_order>();
            this.st_stock = new HashSet<st_stock>();
        }
    
        public int in_inventory_id { get; set; }

        [Display(Name = "类型")]
        public string in_inventory_type { get; set; }

        [Required]
        [Display(Name = "用户名")]
        public string us_user_name { get; set; }

        [Required(ErrorMessage = "创建时间不能为空")]
        [Display(Name = "创建时间")]
        public System.DateTime in_create_time { get; set; }

        [Display(Name = "图片")]
        public byte[] in_image { get; set; }

        [Display(Name = "货号")]
        public string in_style_id { get; set; }
        public string in_style_name { get; set; }

        [Required]
        [Display(Name = "状态")]
        public string in_status { get; set; }

        [Display(Name = "颜色")]
        public string in_color { get; set; }

        [Display(Name = "尺码")]
        public string in_size { get; set; }

        [Display(Name = "EUR")]
        public Nullable<double> in_eur { get; set; }

        [Display(Name = "USD")]
        public Nullable<double> in_usd { get; set; }

        [Display(Name = "CNY")]
        public Nullable<double> in_cny { get; set; }

        [Display(Name = "总数")]
        public Nullable<int> in_amount { get; set; }

        [Display(Name = "备注")]
        public string in_remark { get; set; }
    
        public virtual ICollection<or_order> or_order { get; set; }
        public virtual ICollection<st_stock> st_stock { get; set; }
    }
}
