//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_Order_Storage
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KN_Order_Storage_Entities : DbContext
    {
        public KN_Order_Storage_Entities()
            : base("name=KN_Order_Storage_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ct_client> ct_client { get; set; }
        public virtual DbSet<fu_function> fu_function { get; set; }
        public virtual DbSet<in_inventory> in_inventory { get; set; }
        public virtual DbSet<or_order> or_order { get; set; }
        public virtual DbSet<rf_role_function_rel> rf_role_function_rel { get; set; }
        public virtual DbSet<ro_role> ro_role { get; set; }
        public virtual DbSet<st_stock> st_stock { get; set; }
        public virtual DbSet<ul_userlog> ul_userlog { get; set; }
        public virtual DbSet<us_user> us_user { get; set; }
    }
}
