//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_Order_Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class or_order
    {
        public or_order()
        {
            this.ul_userlog = new HashSet<ul_userlog>();
        }
    
        public int or_order_id { get; set; }
        public Nullable<int> ct_client_id { get; set; }
        public string or_order_type { get; set; }
        public Nullable<int> in_inventory_id { get; set; }
        public string or_status { get; set; }
        public string or_from { get; set; }
        public Nullable<System.DateTime> or_order_time { get; set; }
        public Nullable<System.DateTime> or_delivered_time { get; set; }
        public string or_style_id { get; set; }
        public string or_style_name { get; set; }
        public string or_handled_by { get; set; }
        public Nullable<double> or_price { get; set; }
        public Nullable<double> or_amount { get; set; }
        public string or_remark { get; set; }
        public Nullable<double> or_s_shoulder { get; set; }
        public Nullable<double> or_s_chest { get; set; }
        public Nullable<double> or_s_waist { get; set; }
        public Nullable<double> or_s_buttocks { get; set; }
        public Nullable<double> or_s_stature { get; set; }
        public Nullable<double> or_s_length { get; set; }
        public Nullable<double> or_s_shoes { get; set; }
        public string or_order_status { get; set; }
    
        public virtual ct_client ct_client { get; set; }
        public virtual in_inventory in_inventory { get; set; }
        public virtual ICollection<ul_userlog> ul_userlog { get; set; }
    }
}
