//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_Order_Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class rf_role_function_rel
    {
        public int rf_id { get; set; }
        public int ro_role_id { get; set; }
        public int fu_function_id { get; set; }
        public string rf_status { get; set; }
    
        public virtual fu_function fu_function { get; set; }
        public virtual ro_role ro_role { get; set; }
    }
}
