//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_Order_Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class st_stock
    {
        public int st_stock_id { get; set; }
        public int in_inventory_id { get; set; }
        public string us_user_name { get; set; }
        public string st_status { get; set; }
        public Nullable<int> st_in_number { get; set; }
        public Nullable<int> st_out_number { get; set; }
        public Nullable<System.DateTime> st_in_time { get; set; }
        public Nullable<System.DateTime> st_out_time { get; set; }
        public string st_remark { get; set; }
    
        public virtual in_inventory in_inventory { get; set; }
    }
}
