//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_Order_Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class ul_userlog
    {
        public int ul_userlog_id { get; set; }
        public string us_user_id { get; set; }
        public int or_order_id { get; set; }
        public System.DateTime ul_log_time { get; set; }
        public string ul_operation { get; set; }
        public string ul_description { get; set; }
    
        public virtual or_order or_order { get; set; }
        public virtual us_user us_user { get; set; }
    }
}
