//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_Order_Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class us_user
    {
        public us_user()
        {
            this.ul_userlog = new HashSet<ul_userlog>();
        }
    
        public string us_user_id { get; set; }
        public int ro_role_id { get; set; }
        public string us_user_name { get; set; }
        public string us_user_password { get; set; }
        public string us_from { get; set; }
        public string us_status { get; set; }
        public System.DateTime us_create_time { get; set; }
        public System.DateTime us_last_login_time { get; set; }
        public string us_last_login_ip { get; set; }
        public string us_remark { get; set; }
    
        public virtual ro_role ro_role { get; set; }
        public virtual ICollection<ul_userlog> ul_userlog { get; set; }
    }
}
